require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'lib/tasks/*.rake'
    - 'lib/tasks/rake_helper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'node_modules/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Enabled: false
  Exclude:
    - 'spec/services/**/*'
    - 'spec/factories/**/*'

Metrics/MethodLength:
  CountComments: false

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false
